[global]
; Override default pid file
pid = /run/php-fpm.pid

; Avoid logs being sent to syslog
error_log = /proc/self/fd/2

; Allow children to stop gracefully when fpm is told to stop (avoids 502s)
process_control_timeout = 30

; Do not daemonize
daemonize = no

[www]
; nginx talks to php-fpm over this unix socket
listen = /var/run/php/php-fpm.sock
listen.owner = appuser
listen.group = appgroup

; Redirect worker logs to stdout
access.log = /proc/self/fd/1
catch_workers_output = yes
decorate_workers_output = no

; Required to allow config-by-environment (Craft reads env vars)
clear_env = no

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Process Management Settings
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
pm = dynamic
pm.max_children = 28
pm.start_servers = 7
pm.min_spare_servers = 7
pm.max_spare_servers = 21

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Healthcheck (matches /ping location in nginx.conf)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
ping.path = /ping
ping.response = ok

; Regional settings
php_value[date.timezone] = "UTC"

; Error reporting settings
php_admin_value[display_errors] = Off
php_admin_value[error_reporting] = "E_ALL & ~E_DEPRECATED & ~E_STRICT"

; Performance settings
php_admin_value[memory_limit] = "256M"
php_admin_value[max_execution_time] = "120"

; Upload settings
php_admin_value[post_max_size] = "50M"
php_admin_value[upload_max_filesize] = "50M"
